// 工具注册表 —— 单一数据源:驱动首页列表、导航、面包屑、sitemap。
// 详见《技术方案.md》§4 与《入门层与开发流程.md》。
// 双语:结构字段(slug/category/related/status)语言无关;文案字段按语言存于 zh/en。
import type { Lang } from '../i18n';

export type Category = 'config' | 'text' | 'dev' | 'design' | 'code' | 'seo';

// 每种语言的文案字段
export interface ToolContent {
  title: string; // 全称(工具页 H1 / SEO 主词)
  short: string; // 短名(面包屑 / 导航)
  desc: string; // 一句话卖点(卡片 + meta description)
  keywords: string[];
  stage: string; // 开发流程阶段
  beginnerIntro: string; // 小白话:这是什么、干什么用
  whenToUse: string; // 什么时候会用到
  whyTool: string; // 为什么用它而不是问 AI
}

export interface Tool {
  slug: string; // 'cron'
  category: Category;
  related?: string[]; // 相关工具 slug(人工关联,可跨分类)。见《内链策略.md》§3
  status: 'live' | 'soon';
  zh: ToolContent;
  en: ToolContent;
}

// 解析后(某语言)的工具:文案字段直接展开,页面代码照旧用 tool.title 等。
export type ResolvedTool = { slug: string; category: Category; related?: string[]; status: 'live' | 'soon' } & ToolContent;

export const categoryLabelsByLang: Record<Lang, Record<Category, string>> = {
  zh: {
    config: '配置生成',
    text: '文本处理',
    dev: '开发辅助',
    design: '设计资源',
    code: '代码文档',
    seo: 'SEO / 站长',
  },
  en: {
    config: 'Config Generators',
    text: 'Text Processing',
    dev: 'Dev Utilities',
    design: 'Design Assets',
    code: 'Code & Docs',
    seo: 'SEO / Webmaster',
  },
};

export const categoryLabels = (lang: Lang) => categoryLabelsByLang[lang];

export const tools: Tool[] = [
  {
    slug: 'cron',
    category: 'config',
    related: ['docker-compose', 'nginx', 'timezone'],
    status: 'live',
    zh: {
      title: 'Cron 表达式生成器',
      short: 'Cron 生成器',
      desc: '可视化生成 crontab,自动人话解释,并预览未来执行时间。',
      keywords: ['cron 生成器', 'crontab 每5分钟', 'cron 表达式解释', 'cron 在线'],
      stage: '⑥ 定时与运维',
      beginnerIntro: '定时任务:让服务器在你设定的时间(比如每天凌晨)自动执行命令,不用人工盯着。',
      whenToUse: '需要定时备份、定时清理、定时跑脚本时,用 cron 表达式描述"什么时候执行"。',
      whyTool: 'AI 可能编错 cron,这里用真实解析库即填即得,还能把 AI 给的表达式粘进来反向验证。',
    },
    en: {
      title: 'Cron Expression Generator',
      short: 'Cron Generator',
      desc: 'Build crontab visually, get a plain-English explanation, and preview upcoming run times.',
      keywords: ['cron generator', 'crontab every 5 minutes', 'cron expression explained', 'cron online'],
      stage: '⑥ Scheduling & Ops',
      beginnerIntro: 'Scheduled jobs: have your server run a command automatically at a time you set (e.g. every midnight), no babysitting required.',
      whenToUse: 'When you need scheduled backups, cleanup, or scripts — a cron expression describes "when to run".',
      whyTool: 'AI can get cron wrong; this uses a real parser so you get instant results, and you can paste an AI answer to verify it.',
    },
  },
  {
    slug: 'regex',
    category: 'text',
    related: ['text-diff', 'table', 'json'],
    status: 'live',
    zh: {
      title: '正则表达式测试器',
      short: '正则测试',
      desc: '实时高亮匹配,分组解释,内置常用模板,粘贴即测。',
      keywords: ['在线正则测试', '正则可视化', '正则 匹配邮箱', 'regex 测试'],
      stage: '③ 数据 / 文本处理',
      beginnerIntro: '正则:用一串规则从文本里匹配或提取内容(如邮箱、手机号),不用写一堆判断。',
      whenToUse: '校验输入、批量提取、查找替换文本时。',
      whyTool: '浏览器原生实时高亮,改一处立刻看到匹配结果,还能验证 AI 写的正则对不对。',
    },
    en: {
      title: 'Regex Tester',
      short: 'Regex Tester',
      desc: 'Live match highlighting, group explanations, built-in templates — paste and test instantly.',
      keywords: ['online regex tester', 'regex visualizer', 'regex match email', 'regex test'],
      stage: '③ Data / Text',
      beginnerIntro: 'Regex: a set of rules to match or extract content from text (emails, phone numbers…) without writing lots of conditionals.',
      whenToUse: 'When validating input, extracting in bulk, or doing find-and-replace on text.',
      whyTool: 'Native browser highlighting updates as you type, so you see matches immediately — and can verify AI-written regex.',
    },
  },
  {
    slug: 'nginx',
    category: 'config',
    related: ['docker-compose', 'cron', 'ip'],
    status: 'live',
    zh: {
      title: 'Nginx 反向代理配置生成器',
      short: 'Nginx 配置',
      desc: '表单生成 server 配置,一键切换 Caddy,支持 HTTPS / WebSocket。',
      keywords: ['nginx 反向代理 配置', 'nginx websocket', 'caddy 反代', 'nginx 配置生成'],
      stage: '⑥ 部署上线',
      beginnerIntro: '反向代理:把用户对你域名的访问转发给后台真正跑的程序,顺便管好 HTTPS。',
      whenToUse: '应用跑在服务器某端口上,想用域名 + 小绿锁对外提供访问时。',
      whyTool: '勾几个选项即出可用配置,不用背指令;AI 常编不存在的参数,这里可直接校验。',
    },
    en: {
      title: 'Nginx Reverse Proxy Config Generator',
      short: 'Nginx Config',
      desc: 'Generate a server block from a form, switch to Caddy in one click, with HTTPS / WebSocket support.',
      keywords: ['nginx reverse proxy config', 'nginx websocket', 'caddy reverse proxy', 'nginx config generator'],
      stage: '⑥ Deploy',
      beginnerIntro: 'Reverse proxy: forward visitors of your domain to the program actually running behind it, and handle HTTPS along the way.',
      whenToUse: 'When your app runs on some port and you want to serve it over a domain with a padlock.',
      whyTool: 'Tick a few options and get a working config — no memorizing directives; AI often invents params, here you can verify.',
    },
  },
  {
    slug: 'docker-compose',
    category: 'config',
    related: ['nginx', 'cron', 'password'],
    status: 'live',
    zh: {
      title: 'Docker Compose 模板生成器',
      short: 'Docker Compose',
      desc: '挑选服务(nginx/postgres/redis…)拼出 compose 文件,复制即用。',
      keywords: ['docker compose 模板', 'docker compose postgres', 'docker-compose.yml'],
      stage: '⑤ 构建 / 打包',
      beginnerIntro: '用一个文件描述你的应用要跑哪些服务(网站、数据库…),一条命令全部启动。',
      whenToUse: '要把应用和依赖一起部署、一键启停时。',
      whyTool: '可视化拼装 + 语法校验,避免 YAML 缩进坑;可校验 AI 生成的 compose 是否合法。',
    },
    en: {
      title: 'Docker Compose Template Generator',
      short: 'Docker Compose',
      desc: 'Pick services (nginx/postgres/redis…) to assemble a compose file, ready to copy.',
      keywords: ['docker compose template', 'docker compose postgres', 'docker-compose.yml'],
      stage: '⑤ Build / Package',
      beginnerIntro: 'Describe which services your app runs (site, database…) in one file, then start them all with a single command.',
      whenToUse: 'When you want to deploy an app with its dependencies and start/stop everything at once.',
      whyTool: 'Visual assembly + syntax checks avoid YAML indentation traps; you can also validate AI-generated compose files.',
    },
  },
  {
    slug: 'timestamp',
    category: 'dev',
    related: ['timezone', 'cron', 'jwt'],
    status: 'live',
    zh: {
      title: 'Unix 时间戳转换',
      short: '时间戳转换',
      desc: 'Unix 时间戳与日期时间互转,自动识别秒/毫秒,含本地与 UTC。',
      keywords: ['时间戳转换', 'unix 时间戳', '时间戳转日期', '当前时间戳'],
      stage: '④ 接口 / 调试',
      beginnerIntro: '时间戳是从 1970 年至今的秒数(或毫秒数),程序里常用它表示时间。这里在时间戳和人类可读日期之间互转。',
      whenToUse: '看到接口返回一串数字的时间、或要把日期转成时间戳存库时。',
      whyTool: '自动识别秒还是毫秒,同时给出本地时区、UTC 和 ISO,不用心算时区。',
    },
    en: {
      title: 'Unix Timestamp Converter',
      short: 'Timestamp',
      desc: 'Convert between Unix timestamps and dates, auto-detect seconds/milliseconds, local and UTC.',
      keywords: ['timestamp converter', 'unix timestamp', 'timestamp to date', 'current timestamp'],
      stage: '④ API / Debug',
      beginnerIntro: 'A timestamp is the number of seconds (or milliseconds) since 1970 — a common way programs represent time. Convert it to and from human-readable dates here.',
      whenToUse: 'When an API returns a number for a time, or you need to turn a date into a timestamp for storage.',
      whyTool: 'Auto-detects seconds vs milliseconds and shows local, UTC and ISO at once — no timezone math in your head.',
    },
  },
  {
    slug: 'base64',
    category: 'text',
    related: ['url-encode', 'jwt', 'dataurl'],
    status: 'live',
    zh: {
      title: 'Base64 编码 / 解码',
      short: 'Base64',
      desc: '文本与 Base64 互转,支持中文(UTF-8),浏览器本地处理。',
      keywords: ['base64 编码', 'base64 解码', 'base64 转换', '在线 base64'],
      stage: '③ 数据 / 文本处理',
      beginnerIntro: 'Base64 是把任意文本/数据编成只含字母数字的字符串的方式,常用于在文本环境里传输数据。',
      whenToUse: '需要把数据塞进 URL、JSON、配置或邮件等纯文本场景时。',
      whyTool: '正确处理中文(UTF-8),即时互转、可复制,不用担心编码错乱。',
    },
    en: {
      title: 'Base64 Encode / Decode',
      short: 'Base64',
      desc: 'Convert text to and from Base64 with full UTF-8 support, processed locally in your browser.',
      keywords: ['base64 encode', 'base64 decode', 'base64 converter', 'online base64'],
      stage: '③ Data / Text',
      beginnerIntro: 'Base64 encodes arbitrary text/data into a string of letters and numbers — handy for moving data through text-only channels.',
      whenToUse: 'When you need to embed data in a URL, JSON, config, or email.',
      whyTool: 'Handles UTF-8 (including CJK) correctly, converts instantly, and is copy-ready — no garbled encodings.',
    },
  },
  {
    slug: 'url-encode',
    category: 'text',
    related: ['base64', 'html-entity', 'json'],
    status: 'live',
    zh: {
      title: 'URL 编码 / 解码',
      short: 'URL 编解码',
      desc: '对 URL 参数进行百分号编码与解码,支持中文与特殊字符。',
      keywords: ['url 编码', 'url 解码', 'urlencode', '百分号编码'],
      stage: '③ 数据 / 文本处理',
      beginnerIntro: 'URL 里不能直接放空格、中文等字符,需要编码成 %xx 形式。这里做 URL 编码与解码。',
      whenToUse: '拼接带中文/特殊字符的链接、或看到 %E4%B8%AD 这类乱码想还原时。',
      whyTool: '即时双向转换,可选整段 URL 或单个参数两种模式,结果准确可复制。',
    },
    en: {
      title: 'URL Encode / Decode',
      short: 'URL Encode',
      desc: 'Percent-encode and decode URL parameters, with support for non-ASCII and special characters.',
      keywords: ['url encode', 'url decode', 'urlencode', 'percent encoding'],
      stage: '③ Data / Text',
      beginnerIntro: "URLs can't contain spaces or non-ASCII characters directly — they're encoded as %xx. Encode and decode URLs here.",
      whenToUse: 'When building links with special characters, or restoring something like %E4%B8%AD back to readable text.',
      whyTool: 'Instant two-way conversion with whole-URL or single-parameter modes — accurate and copy-ready.',
    },
  },
  {
    slug: 'uuid',
    category: 'dev',
    related: ['hash', 'password', 'jwt'],
    status: 'live',
    zh: {
      title: 'UUID 生成器',
      short: 'UUID 生成',
      desc: '批量生成 UUID v4,支持大写、去连字符,一键复制。',
      keywords: ['uuid 生成', 'guid 生成', 'uuid v4', '在线 uuid'],
      stage: '④ 接口 / 调试',
      beginnerIntro: 'UUID 是一串几乎不会重复的唯一标识,常用作数据库主键、请求 ID 等。',
      whenToUse: '需要一个全局唯一的 ID,又不想依赖数据库自增时。',
      whyTool: '用浏览器原生 crypto 生成,安全随机;可批量生成并一键复制。',
    },
    en: {
      title: 'UUID Generator',
      short: 'UUID',
      desc: 'Generate UUID v4 in bulk, with uppercase and hyphen-free options, copy in one click.',
      keywords: ['uuid generator', 'guid generator', 'uuid v4', 'online uuid'],
      stage: '④ API / Debug',
      beginnerIntro: 'A UUID is a practically-never-repeating unique identifier, often used as a database primary key or request ID.',
      whenToUse: 'When you need a globally unique ID without relying on database auto-increment.',
      whyTool: "Generated with the browser's native crypto for secure randomness; batch-generate and copy in one click.",
    },
  },
  {
    slug: 'json',
    category: 'text',
    related: ['table', 'text-diff', 'url-encode'],
    status: 'live',
    zh: {
      title: 'JSON 格式化 / 校验',
      short: 'JSON 格式化',
      desc: '格式化、压缩、校验 JSON,可排序键名,错误精准定位。',
      keywords: ['json 格式化', 'json 校验', 'json 压缩', '在线 json'],
      stage: '③ 数据 / 文本处理',
      beginnerIntro: 'JSON 是接口和配置最常用的数据格式。这里把压成一行的 JSON 展开成易读格式,或反过来压缩,并校验是否合法。',
      whenToUse: '接口返回一坨挤在一起的 JSON、或要检查 JSON 写得对不对时。',
      whyTool: '本地即时格式化、语法报错定位;可校验 AI 生成的 JSON 是否合法。',
    },
    en: {
      title: 'JSON Formatter / Validator',
      short: 'JSON Formatter',
      desc: 'Format, minify and validate JSON, sort keys, with precise error location.',
      keywords: ['json formatter', 'json validator', 'json minify', 'online json'],
      stage: '③ Data / Text',
      beginnerIntro: 'JSON is the most common data format for APIs and configs. Expand one-line JSON into a readable layout (or minify it) and check it is valid.',
      whenToUse: 'When an API returns a wall of cramped JSON, or you need to check that JSON is written correctly.',
      whyTool: 'Instant local formatting with syntax-error location; also validates AI-generated JSON.',
    },
  },
  {
    slug: 'jwt',
    category: 'dev',
    related: ['base64', 'timestamp', 'hash'],
    status: 'live',
    zh: {
      title: 'JWT 解码器',
      short: 'JWT 解码',
      desc: '解析 JWT 的 Header 与 Payload,自动展示过期/签发时间。',
      keywords: ['jwt 解码', 'jwt 解析', 'token 解析', '在线 jwt'],
      stage: '④ 接口 / 调试',
      beginnerIntro: 'JWT 是登录后常见的一串 token,里面用 Base64 编了用户信息和有效期。这里把它解开看内容。',
      whenToUse: '调试登录/鉴权,想看 token 里存了什么、什么时候过期时。',
      whyTool: '本地解析不外传 token;自动把 exp/iat 时间戳转成可读日期,一眼看懂。',
    },
    en: {
      title: 'JWT Decoder',
      short: 'JWT Decoder',
      desc: 'Decode a JWT header and payload, with expiry/issued times shown automatically.',
      keywords: ['jwt decoder', 'jwt decode', 'token decode', 'online jwt'],
      stage: '④ API / Debug',
      beginnerIntro: 'A JWT is the token you often get after logging in — it Base64-encodes user info and an expiry. Decode it to see the contents here.',
      whenToUse: 'When debugging login/auth and you want to see what a token stores and when it expires.',
      whyTool: 'Decoded locally — your token never leaves the browser; exp/iat timestamps are turned into readable dates automatically.',
    },
  },
  {
    slug: 'gradient',
    category: 'design',
    related: ['color', 'contrast', 'playground'],
    status: 'live',
    zh: {
      title: 'CSS 渐变生成器',
      short: 'CSS 渐变',
      desc: '可视化调节颜色与角度,实时预览并生成 CSS 渐变代码。',
      keywords: ['css 渐变', 'linear-gradient 生成', '渐变背景 css', 'gradient generator'],
      stage: '① 设计 / 资源',
      beginnerIntro: '渐变就是颜色平滑过渡的背景。这里拖一拖就生成对应的 CSS 代码。',
      whenToUse: '想给按钮、卡片或页面背景做个渐变色时。',
      whyTool: '所见即所得,实时预览 + 直接出 CSS,不用背 linear-gradient 语法。',
    },
    en: {
      title: 'CSS Gradient Generator',
      short: 'CSS Gradient',
      desc: 'Adjust colors and angle visually, preview live, and generate CSS gradient code.',
      keywords: ['css gradient', 'linear-gradient generator', 'gradient background css', 'gradient generator'],
      stage: '① Design / Assets',
      beginnerIntro: 'A gradient is a background that fades smoothly between colors. Drag a bit and get the matching CSS.',
      whenToUse: 'When you want a gradient for a button, card, or page background.',
      whyTool: 'What-you-see-is-what-you-get: live preview and ready CSS, no memorizing linear-gradient syntax.',
    },
  },
  {
    slug: 'color',
    category: 'design',
    related: ['gradient', 'contrast', 'colorblind'],
    status: 'live',
    zh: {
      title: '颜色转换器',
      short: '颜色转换',
      desc: 'HEX / RGB / HSL 互转,预览色块,并生成同色系深浅色阶。',
      keywords: ['颜色转换', 'hex 转 rgb', 'rgb 转 hsl', '颜色代码转换'],
      stage: '① 设计 / 资源',
      beginnerIntro: '在 HEX(#ff0000)、RGB、HSL 等颜色写法之间转换,并预览颜色。',
      whenToUse: '设计里拿到一种格式的颜色,代码里却要另一种格式时。',
      whyTool: '一次看到三种格式 + 色块预览 + 深浅色阶,点一下即复制。',
    },
    en: {
      title: 'Color Converter',
      short: 'Color Converter',
      desc: 'Convert between HEX / RGB / HSL, preview swatches, and generate a tint/shade scale.',
      keywords: ['color converter', 'hex to rgb', 'rgb to hsl', 'color code converter'],
      stage: '① Design / Assets',
      beginnerIntro: 'Convert colors between HEX (#ff0000), RGB, HSL and more, and preview them.',
      whenToUse: 'When a design gives you a color in one format but your code needs another.',
      whyTool: 'See all three formats plus a swatch and a tint/shade scale at once — click to copy.',
    },
  },
  {
    slug: 'image-compress',
    category: 'design',
    related: ['svg', 'dataurl', 'favicon'],
    status: 'live',
    zh: {
      title: '图片压缩',
      short: '图片压缩',
      desc: '本地压缩 JPG / PNG / WebP,可调质量与尺寸,不上传服务器。',
      keywords: ['图片压缩', '在线压缩图片', 'webp 转换', '图片变小'],
      stage: '① 设计 / 资源',
      beginnerIntro: '在基本不影响观感的前提下,把图片文件变小,加快网页加载。',
      whenToUse: '图片太大拖慢网站,或要满足上传大小限制时。',
      whyTool: '全程在浏览器本地压缩,图片不上传,隐私安全且即时出结果。',
    },
    en: {
      title: 'Image Compressor',
      short: 'Image Compress',
      desc: 'Compress JPG / PNG / WebP locally with adjustable quality and size — nothing uploaded.',
      keywords: ['image compressor', 'compress image online', 'webp converter', 'reduce image size'],
      stage: '① Design / Assets',
      beginnerIntro: 'Make image files smaller with barely any visible loss, so pages load faster.',
      whenToUse: 'When large images slow your site, or you need to meet an upload size limit.',
      whyTool: 'Compressed entirely in your browser — images never leave your device — with instant results.',
    },
  },
  {
    slug: 'markdown-table',
    category: 'code',
    related: ['table', 'html-to-markdown', 'tree'],
    status: 'live',
    zh: {
      title: 'Markdown 表格生成器',
      short: 'MD 表格',
      desc: '可视化填表格 + 设置列对齐,实时生成 Markdown 表格代码。',
      keywords: ['markdown 表格', 'md 表格生成', 'markdown table 生成器'],
      stage: '② 编码 / 演练',
      beginnerIntro: 'Markdown 手写表格容易对不齐。这里填个表格,自动生成规整的 Markdown 代码。',
      whenToUse: '在 README、文档或 GitHub issue 里要插入表格时。',
      whyTool: '可视化编辑 + 列对齐设置,自动对齐生成,免手敲竖线和分隔线。',
    },
    en: {
      title: 'Markdown Table Generator',
      short: 'MD Table',
      desc: 'Fill a table visually, set column alignment, and get clean Markdown table code in real time.',
      keywords: ['markdown table', 'md table generator', 'markdown table maker'],
      stage: '② Coding / Playground',
      beginnerIntro: 'Hand-writing Markdown tables is fiddly to align. Fill in a grid and get tidy Markdown automatically.',
      whenToUse: 'When you need to insert a table into a README, docs, or a GitHub issue.',
      whyTool: 'Visual editing plus alignment settings auto-format the output — no typing pipes and dashes by hand.',
    },
  },
  {
    slug: 'password',
    category: 'dev',
    related: ['hash', 'uuid', 'jwt'],
    status: 'live',
    zh: {
      title: '密码生成器',
      short: '密码生成',
      desc: '生成高强度随机密码,可选长度与字符集,基于安全随机源。',
      keywords: ['密码生成器', '随机密码', '强密码生成', 'password generator'],
      stage: '④ 接口 / 调试',
      beginnerIntro: '生成又长又随机、难被猜到的密码。',
      whenToUse: '注册账号、设置数据库或服务器密码时。',
      whyTool: '用浏览器安全随机源本地生成,不联网、不记录,可调长度与字符集。',
    },
    en: {
      title: 'Password Generator',
      short: 'Password',
      desc: 'Generate strong random passwords with adjustable length and character sets, from a secure source.',
      keywords: ['password generator', 'random password', 'strong password generator', 'password generator'],
      stage: '④ API / Debug',
      beginnerIntro: 'Generate long, random passwords that are hard to guess.',
      whenToUse: 'When signing up for an account or setting a database/server password.',
      whyTool: "Generated locally from the browser's secure random source — offline, unlogged, with adjustable length and character sets.",
    },
  },
  {
    slug: 'hash',
    category: 'dev',
    related: ['uuid', 'password', 'base64'],
    status: 'live',
    zh: {
      title: 'Hash 生成器',
      short: 'Hash 生成',
      desc: '计算文本的 SHA-1 / SHA-256 / SHA-384 / SHA-512 哈希值。',
      keywords: ['hash 生成', 'sha256 在线', '哈希计算', 'sha512'],
      stage: '④ 接口 / 调试',
      beginnerIntro: '把任意文本转成固定长度的"指纹"(哈希),常用于校验一致性。',
      whenToUse: '校验文件/文本是否被改动,或存储密码摘要时。',
      whyTool: '基于浏览器原生 Web Crypto 本地计算,数据不外传。',
    },
    en: {
      title: 'Hash Generator',
      short: 'Hash',
      desc: 'Compute SHA-1 / SHA-256 / SHA-384 / SHA-512 hashes of text.',
      keywords: ['hash generator', 'sha256 online', 'hash calculator', 'sha512'],
      stage: '④ API / Debug',
      beginnerIntro: 'Turn any text into a fixed-length "fingerprint" (hash), commonly used to check integrity.',
      whenToUse: 'When verifying a file/text was not modified, or storing a password digest.',
      whyTool: "Computed locally with the browser's native Web Crypto — your data never leaves the page.",
    },
  },
  {
    slug: 'timezone',
    category: 'dev',
    related: ['timestamp', 'cron', 'ip'],
    status: 'live',
    zh: {
      title: '时区转换器',
      short: '时区转换',
      desc: '把一个时间换算到全球多个时区,自动处理夏令时。',
      keywords: ['时区转换', 'utc 转北京时间', '时差换算', 'timezone converter'],
      stage: '④ 接口 / 调试',
      beginnerIntro: '把某个时间点换算成不同城市/时区的当地时间。',
      whenToUse: '跨时区安排会议,或看国外服务器/日志时间时。',
      whyTool: '基于浏览器 Intl 时区库,自动处理夏令时,即时换算。',
    },
    en: {
      title: 'Timezone Converter',
      short: 'Timezone',
      desc: 'Convert one time across multiple world timezones, with daylight saving handled automatically.',
      keywords: ['timezone converter', 'utc to local time', 'time difference calculator', 'timezone converter'],
      stage: '④ API / Debug',
      beginnerIntro: 'Convert a moment in time into the local time of different cities/timezones.',
      whenToUse: 'When scheduling meetings across timezones, or reading times in foreign server logs.',
      whyTool: "Uses the browser's Intl timezone database, handles DST automatically, and converts instantly.",
    },
  },
  {
    slug: 'tree',
    category: 'dev',
    related: ['markdown-table', 'json', 'docker-compose'],
    status: 'live',
    zh: {
      title: '目录树生成器',
      short: '目录树',
      desc: '把缩进列表转成 ├── └── 形式的 ASCII 目录树。',
      keywords: ['目录树生成', 'ascii 树', '文件结构 树状图', 'tree 生成'],
      stage: '⑤ 构建 / 打包',
      beginnerIntro: '把用缩进写的文件/目录列表,变成漂亮的树状图。',
      whenToUse: '写 README 展示项目结构时。',
      whyTool: '边写边出树状图,复制即用,免手敲制表符和连线。',
    },
    en: {
      title: 'Directory Tree Generator',
      short: 'Dir Tree',
      desc: 'Turn an indented list into an ASCII directory tree with ├── └── connectors.',
      keywords: ['directory tree generator', 'ascii tree', 'file structure diagram', 'tree generator'],
      stage: '⑤ Build / Package',
      beginnerIntro: 'Turn an indented list of files/folders into a nice tree diagram.',
      whenToUse: 'When showing your project structure in a README.',
      whyTool: 'The tree updates as you type and is copy-ready — no typing tabs and connector lines by hand.',
    },
  },
  {
    slug: 'ua',
    category: 'dev',
    related: ['ip', 'timezone', 'json'],
    status: 'live',
    zh: {
      title: 'UserAgent 解析器',
      short: 'UA 解析',
      desc: '解析 User-Agent 字符串,识别浏览器、系统与设备类型。',
      keywords: ['useragent 解析', 'ua 解析', 'user-agent 查询'],
      stage: '④ 接口 / 调试',
      beginnerIntro: 'User-Agent 是浏览器自报身份的一串文本。这里把它解析成浏览器/系统等信息。',
      whenToUse: '排查兼容性问题,或看日志里的 UA 时。',
      whyTool: '默认填入你当前浏览器的 UA,本地解析,不上传。',
    },
    en: {
      title: 'User-Agent Parser',
      short: 'UA Parser',
      desc: 'Parse a User-Agent string to identify the browser, OS, and device type.',
      keywords: ['useragent parser', 'ua parser', 'user-agent lookup'],
      stage: '④ API / Debug',
      beginnerIntro: 'A User-Agent is the string a browser uses to identify itself. Parse it into browser/OS details here.',
      whenToUse: 'When troubleshooting compatibility issues, or reading UAs in your logs.',
      whyTool: "Pre-filled with your current browser's UA, parsed locally, nothing uploaded.",
    },
  },
  {
    slug: 'meta',
    category: 'seo',
    related: ['og', 'qrcode', 'favicon'],
    status: 'live',
    zh: {
      title: 'Meta 标签长度检测',
      short: 'Meta 检测',
      desc: '检测 title/description 的字符与像素长度,并预览 Google 搜索结果。',
      keywords: ['title 长度检测', 'meta description 长度', 'serp 预览', 'seo 标题'],
      stage: '⑧ 发布 / SEO',
      beginnerIntro: 'SEO 里标题和描述太长会被搜索引擎截断。这里检测长度并预览显示效果。',
      whenToUse: '给网页写 SEO 标题和描述时。',
      whyTool: '同时看字符数、像素宽度和搜索结果预览,超限即时提示。',
    },
    en: {
      title: 'Meta Tag Length Checker',
      short: 'Meta Check',
      desc: 'Check title/description length in characters and pixels, with a Google result preview.',
      keywords: ['title length checker', 'meta description length', 'serp preview', 'seo title'],
      stage: '⑧ Publish / SEO',
      beginnerIntro: 'In SEO, titles and descriptions that are too long get truncated by search engines. Check length and preview how it looks here.',
      whenToUse: 'When writing the SEO title and description for a page.',
      whyTool: 'See character count, pixel width, and a search-result preview at once, with instant over-limit warnings.',
    },
  },
  {
    slug: 'ip',
    category: 'dev',
    related: ['ua', 'nginx', 'timezone'],
    status: 'live',
    zh: {
      title: 'IP 地址查询',
      short: 'IP 查询',
      desc: '查询你的公网 IP 及归属地、运营商等信息。',
      keywords: ['ip 查询', '公网 ip', '我的 ip', 'ip 归属地'],
      stage: '④ 接口 / 调试',
      beginnerIntro: '查看你当前的公网 IP 地址,以及它的大致归属地和运营商。',
      whenToUse: '排查网络、确认出口 IP、检查是否走了代理时。',
      whyTool: '需要服务器才能看到你的公网 IP,由 DevBox 后端返回,不记录你的查询。',
    },
    en: {
      title: 'IP Address Lookup',
      short: 'IP Lookup',
      desc: 'Look up your public IP along with its location, ISP, and more.',
      keywords: ['ip lookup', 'public ip', 'what is my ip', 'ip location'],
      stage: '④ API / Debug',
      beginnerIntro: 'See your current public IP address, plus its approximate location and ISP.',
      whenToUse: 'When troubleshooting networking, confirming your egress IP, or checking whether a proxy is in use.',
      whyTool: 'Seeing your public IP requires a server; DevBox returns it from the backend and does not log your query.',
    },
  },
  {
    slug: 'qrcode',
    category: 'design',
    related: ['og', 'meta', 'favicon'],
    status: 'live',
    zh: {
      title: '二维码生成器',
      short: '二维码生成',
      desc: '把文本 / 链接生成二维码,可调尺寸与容错级别,下载 PNG。',
      keywords: ['二维码生成', '在线二维码', 'qrcode 生成', '网址转二维码'],
      stage: '⑧ 发布 / SEO',
      beginnerIntro: '把一段文字或网址变成二维码图片,手机扫一扫就能打开。',
      whenToUse: '要让别人扫码访问链接、加好友、看名片时。',
      whyTool: '本地即时生成、可下载 PNG,内容不上传服务器。',
    },
    en: {
      title: 'QR Code Generator',
      short: 'QR Code',
      desc: 'Turn text / links into a QR code with adjustable size and error correction, download as PNG.',
      keywords: ['qr code generator', 'online qr code', 'qrcode generator', 'url to qr code'],
      stage: '⑧ Publish / SEO',
      beginnerIntro: 'Turn a piece of text or a URL into a QR code image that a phone can scan to open.',
      whenToUse: 'When you want people to scan a link, add a contact, or view a card.',
      whyTool: 'Generated locally and downloadable as PNG — the content is never uploaded.',
    },
  },
  {
    slug: 'og',
    category: 'seo',
    related: ['meta', 'qrcode', 'favicon'],
    status: 'live',
    zh: {
      title: 'Open Graph 预览',
      short: 'OG 预览',
      desc: '预览分享到社交平台的卡片效果,并生成 OG / Twitter 标签。',
      keywords: ['open graph 预览', 'og 标签生成', '分享卡片预览', 'og image'],
      stage: '⑧ 发布 / SEO',
      beginnerIntro: '网页被分享到微信/X 等平台时会显示一张卡片,这里预览它并生成对应标签。',
      whenToUse: '做完页面、想让分享出去好看时。',
      whyTool: '实时预览卡片 + 一键生成 og:/twitter: 标签,免反复发帖测试。',
    },
    en: {
      title: 'Open Graph Preview',
      short: 'OG Preview',
      desc: 'Preview how your page looks as a social share card, and generate OG / Twitter tags.',
      keywords: ['open graph preview', 'og tags generator', 'share card preview', 'og image'],
      stage: '⑧ Publish / SEO',
      beginnerIntro: 'When a page is shared on platforms like X or WeChat, it shows a card. Preview it and generate the matching tags here.',
      whenToUse: "When a page is done and you want it to look good when shared.",
      whyTool: 'Live card preview plus one-click og:/twitter: tags — no repeated test posts.',
    },
  },
  {
    slug: 'semver',
    category: 'dev',
    related: ['json', 'docker-compose', 'uuid'],
    status: 'live',
    zh: {
      title: 'Semver 版本工具',
      short: 'Semver',
      desc: '校验语义化版本、判断是否满足范围、解析与比较版本号。',
      keywords: ['semver', '语义化版本', '版本范围 满足', 'npm 版本'],
      stage: '⑤ 构建 / 打包',
      beginnerIntro: 'Semver 是 1.2.3 这样的版本号规则。这里判断版本是否合法、是否满足 ^1.0.0 之类的范围。',
      whenToUse: '看 package.json 依赖范围、确认某版本是否匹配时。',
      whyTool: '基于官方 semver 库本地计算,范围判断准确,免手算。',
    },
    en: {
      title: 'Semver Version Tool',
      short: 'Semver',
      desc: 'Validate semantic versions, test range satisfaction, and parse and compare version numbers.',
      keywords: ['semver', 'semantic versioning', 'version range satisfies', 'npm version'],
      stage: '⑤ Build / Package',
      beginnerIntro: 'Semver is the versioning scheme like 1.2.3. Check whether a version is valid or satisfies a range like ^1.0.0.',
      whenToUse: 'When reading package.json dependency ranges, or confirming a version matches.',
      whyTool: 'Computed locally with the official semver library — accurate range checks, no manual math.',
    },
  },
  {
    slug: 'html-to-markdown',
    category: 'code',
    related: ['markdown-table', 'html-entity', 'playground'],
    status: 'live',
    zh: {
      title: 'HTML 转 Markdown',
      short: 'HTML→MD',
      desc: '把 HTML 转换成 Markdown,保留标题、列表、链接、代码等。',
      keywords: ['html 转 markdown', 'html to markdown', '网页转 md'],
      stage: '② 编码 / 演练',
      beginnerIntro: '把一段 HTML 代码转成等价的 Markdown 文本。',
      whenToUse: '把网页内容搬进 Markdown 文档/笔记时。',
      whyTool: '本地即时转换,保留结构,可校验 AI 转出来的 Markdown 是否正确。',
    },
    en: {
      title: 'HTML to Markdown',
      short: 'HTML→MD',
      desc: 'Convert HTML into Markdown, preserving headings, lists, links, code, and more.',
      keywords: ['html to markdown', 'convert html to markdown', 'web page to md'],
      stage: '② Coding / Playground',
      beginnerIntro: 'Convert a chunk of HTML into equivalent Markdown text.',
      whenToUse: 'When moving web content into a Markdown doc or notes.',
      whyTool: 'Instant local conversion that preserves structure — and lets you verify AI-generated Markdown.',
    },
  },
  {
    slug: 'playground',
    category: 'code',
    related: ['gradient', 'color', 'html-to-markdown'],
    status: 'live',
    zh: {
      title: '代码演练场(HTML/CSS/JS)',
      short: '代码演练',
      desc: '在线编写 HTML/CSS/JS,右侧沙箱实时预览效果。',
      keywords: ['html 在线运行', 'css js 演练', '前端 playground', '在线代码运行'],
      stage: '② 编码 / 演练',
      beginnerIntro: '一个能马上看到效果的前端练习场:左边写 HTML/CSS/JS,右边实时显示。',
      whenToUse: '快速试一段样式/脚本、做最小复现时。',
      whyTool: '在隔离沙箱里运行,即写即看,代码不上传。',
    },
    en: {
      title: 'Code Playground (HTML/CSS/JS)',
      short: 'Playground',
      desc: 'Write HTML/CSS/JS online with a live sandbox preview on the right.',
      keywords: ['run html online', 'css js playground', 'frontend playground', 'run code online'],
      stage: '② Coding / Playground',
      beginnerIntro: 'A frontend scratchpad with instant feedback: write HTML/CSS/JS on the left, see it live on the right.',
      whenToUse: 'When quickly trying out some styling/script or building a minimal repro.',
      whyTool: 'Runs in an isolated sandbox with instant preview — your code is never uploaded.',
    },
  },
  {
    slug: 'favicon',
    category: 'design',
    related: ['svg', 'image-compress', 'qrcode'],
    status: 'live',
    zh: {
      title: 'Favicon 生成器',
      short: 'Favicon',
      desc: '上传图片生成多尺寸 PNG 图标,并给出 HTML 引用代码。',
      keywords: ['favicon 生成', '网站图标生成', 'favicon 制作', '图标尺寸'],
      stage: '① 设计 / 资源',
      beginnerIntro: 'Favicon 是浏览器标签页上的小图标。上传一张图,生成各种尺寸。',
      whenToUse: '给网站配标签页图标时。',
      whyTool: '本地用 Canvas 生成各尺寸并给出引用代码,图片不上传。',
    },
    en: {
      title: 'Favicon Generator',
      short: 'Favicon',
      desc: 'Upload an image to generate multi-size PNG icons, with the HTML reference code.',
      keywords: ['favicon generator', 'website icon generator', 'make favicon', 'icon sizes'],
      stage: '① Design / Assets',
      beginnerIntro: 'A favicon is the little icon on a browser tab. Upload an image and generate all the sizes.',
      whenToUse: 'When setting a tab icon for your site.',
      whyTool: 'Generated locally with Canvas at every size, with reference code — images are not uploaded.',
    },
  },
  {
    slug: 'svg',
    category: 'design',
    related: ['favicon', 'image-compress', 'dataurl'],
    status: 'live',
    zh: {
      title: 'SVG 压缩',
      short: 'SVG 压缩',
      desc: '去除注释与冗余空白,压缩 SVG 体积,显示压缩前后大小。',
      keywords: ['svg 压缩', 'svg 优化', 'svg 变小', 'svg minify'],
      stage: '① 设计 / 资源',
      beginnerIntro: '把 SVG 图标里多余的注释和空白去掉,让文件更小。',
      whenToUse: '把 SVG 图标放进项目、想减小体积时。',
      whyTool: '本地即时压缩、可复制,展示压缩率,数据不上传。',
    },
    en: {
      title: 'SVG Minifier',
      short: 'SVG Minify',
      desc: 'Strip comments and redundant whitespace to shrink SVGs, showing before/after size.',
      keywords: ['svg minify', 'svg optimizer', 'shrink svg', 'svg minify'],
      stage: '① Design / Assets',
      beginnerIntro: 'Remove unnecessary comments and whitespace from an SVG icon to make the file smaller.',
      whenToUse: 'When adding an SVG icon to your project and wanting to reduce its size.',
      whyTool: 'Instant local minification, copy-ready, with the compression ratio shown — nothing uploaded.',
    },
  },
  {
    slug: 'text-diff',
    category: 'text',
    related: ['regex', 'json', 'table'],
    status: 'live',
    zh: {
      title: '文本 Diff 对比',
      short: '文本 Diff',
      desc: '逐行比较两段文本,高亮新增、删除与修改,统计差异。',
      keywords: ['文本对比', 'diff 在线', '文本差异', '代码对比'],
      stage: '③ 数据 / 文本处理',
      beginnerIntro: '把两段文本并排比,标出哪些行加了、删了、改了。',
      whenToUse: '对比两个版本的配置/代码/文案有什么不同时。',
      whyTool: '本地即时逐行 diff,颜色高亮一目了然,内容不上传。',
    },
    en: {
      title: 'Text Diff',
      short: 'Text Diff',
      desc: 'Compare two texts line by line, highlighting additions, deletions, and changes, with stats.',
      keywords: ['text compare', 'diff online', 'text difference', 'code compare'],
      stage: '③ Data / Text',
      beginnerIntro: 'Compare two texts side by side and mark which lines were added, removed, or changed.',
      whenToUse: 'When comparing two versions of a config/code/copy to see what differs.',
      whyTool: 'Instant local line-by-line diff with clear color highlighting — content is never uploaded.',
    },
  },
  {
    slug: 'table',
    category: 'text',
    related: ['json', 'markdown-table', 'text-diff'],
    status: 'live',
    zh: {
      title: '表格转换器',
      short: '表格转换',
      desc: 'CSV / JSON / Markdown / YAML / HTML 表格任意互转,复制即用。',
      keywords: ['csv 转 json', 'json 转 markdown', 'csv 转 markdown', '表格转换'],
      stage: '③ 数据 / 文本处理',
      beginnerIntro: '把表格数据在 CSV、JSON、Markdown、YAML、HTML 等格式之间来回转换。',
      whenToUse: '拿到一种格式的表格数据,却要另一种格式时。',
      whyTool: '五种格式两两互转、本地即时处理;可校验 AI 转出来的结构是否正确。',
    },
    en: {
      title: 'Table Converter',
      short: 'Table Convert',
      desc: 'Convert tables between CSV / JSON / Markdown / YAML / HTML in any direction, ready to copy.',
      keywords: ['csv to json', 'json to markdown', 'csv to markdown', 'table converter'],
      stage: '③ Data / Text',
      beginnerIntro: 'Convert table data back and forth between CSV, JSON, Markdown, YAML, and HTML.',
      whenToUse: 'When you have table data in one format but need it in another.',
      whyTool: 'Any-to-any across five formats, processed locally; also validates AI-converted structures.',
    },
  },
  {
    slug: 'contrast',
    category: 'design',
    related: ['color', 'colorblind', 'gradient'],
    status: 'live',
    zh: {
      title: '颜色对比度检测',
      short: '对比度检测',
      desc: '计算两色对比度,按 WCAG 判断可读性(AA/AAA)。',
      keywords: ['对比度计算', 'wcag 对比度', '颜色可读性', 'contrast ratio'],
      stage: '① 设计 / 资源',
      beginnerIntro: '检查文字色和背景色的对比够不够,避免看不清。',
      whenToUse: '定文字/背景配色、做无障碍(a11y)检查时。',
      whyTool: '按 WCAG 标准即时给出对比度和 AA/AAA 是否达标。',
    },
    en: {
      title: 'Color Contrast Checker',
      short: 'Contrast',
      desc: 'Compute the contrast ratio of two colors and judge readability against WCAG (AA/AAA).',
      keywords: ['contrast checker', 'wcag contrast', 'color readability', 'contrast ratio'],
      stage: '① Design / Assets',
      beginnerIntro: 'Check whether the contrast between text and background colors is enough to be readable.',
      whenToUse: 'When choosing text/background colors or doing an accessibility (a11y) check.',
      whyTool: 'Instantly gives the contrast ratio and whether it meets WCAG AA/AAA.',
    },
  },
  {
    slug: 'colorblind',
    category: 'design',
    related: ['contrast', 'color', 'gradient'],
    status: 'live',
    zh: {
      title: '色盲模拟',
      short: '色盲模拟',
      desc: '模拟颜色在红绿色盲等色觉障碍下的显示效果。',
      keywords: ['色盲模拟', '色觉障碍', '色盲 颜色', 'color blindness'],
      stage: '① 设计 / 资源',
      beginnerIntro: '看看你的配色在色盲用户眼里大概是什么样。',
      whenToUse: '做无障碍设计、确认配色是否易区分时。',
      whyTool: '即时模拟多种色觉类型,帮你避开难以区分的配色。',
    },
    en: {
      title: 'Color Blindness Simulator',
      short: 'Colorblind',
      desc: 'Simulate how colors appear under red-green and other color-vision deficiencies.',
      keywords: ['color blindness simulator', 'color vision deficiency', 'colorblind colors', 'color blindness'],
      stage: '① Design / Assets',
      beginnerIntro: 'See roughly how your color scheme looks to colorblind users.',
      whenToUse: 'When designing for accessibility or confirming colors are easy to tell apart.',
      whyTool: 'Instantly simulates several color-vision types to help you avoid hard-to-distinguish palettes.',
    },
  },
  {
    slug: 'html-entity',
    category: 'text',
    related: ['url-encode', 'unicode', 'html-to-markdown'],
    status: 'live',
    zh: {
      title: 'HTML 实体编解码',
      short: 'HTML 实体',
      desc: '在字符与 HTML 实体(&amp; &#39; 等)之间互转。',
      keywords: ['html 实体', 'html 转义', 'html entity 编码', '实体解码'],
      stage: '③ 数据 / 文本处理',
      beginnerIntro: '把 < > & 等特殊字符转成 HTML 实体,或反过来还原。',
      whenToUse: '把代码/符号安全地放进 HTML,或还原网页里的实体时。',
      whyTool: '即时双向转换,浏览器本地处理。',
    },
    en: {
      title: 'HTML Entity Encode / Decode',
      short: 'HTML Entity',
      desc: 'Convert between characters and HTML entities (&amp; &#39; etc.).',
      keywords: ['html entities', 'html escape', 'html entity encode', 'entity decode'],
      stage: '③ Data / Text',
      beginnerIntro: 'Turn special characters like < > & into HTML entities, or restore them.',
      whenToUse: 'When safely placing code/symbols into HTML, or restoring entities from a web page.',
      whyTool: 'Instant two-way conversion, processed locally in the browser.',
    },
  },
  {
    slug: 'unicode',
    category: 'text',
    related: ['ascii', 'html-entity', 'base64'],
    status: 'live',
    zh: {
      title: 'Unicode / 编码查看',
      short: 'Unicode 查看',
      desc: '查看文本的 Unicode 码点与 UTF-8 / UTF-16 编码。',
      keywords: ['unicode 码点', 'utf-8 编码', '字符编码查看', 'code point'],
      stage: '③ 数据 / 文本处理',
      beginnerIntro: '看一段文字里每个字符的 Unicode 码点和字节编码。',
      whenToUse: '排查乱码、看 emoji/特殊字符编码时。',
      whyTool: '逐字符列出码点与 UTF-8/16 字节,本地即时计算。',
    },
    en: {
      title: 'Unicode / Encoding Inspector',
      short: 'Unicode',
      desc: 'Inspect the Unicode code points and UTF-8 / UTF-16 encoding of text.',
      keywords: ['unicode code point', 'utf-8 encoding', 'character encoding inspector', 'code point'],
      stage: '③ Data / Text',
      beginnerIntro: 'See the Unicode code point and byte encoding of every character in a string.',
      whenToUse: 'When debugging garbled text, or inspecting emoji/special-character encodings.',
      whyTool: 'Lists code points and UTF-8/16 bytes per character, computed instantly and locally.',
    },
  },
  {
    slug: 'ascii',
    category: 'text',
    related: ['unicode', 'html-entity', 'base64'],
    status: 'live',
    zh: {
      title: 'ASCII 码表',
      short: 'ASCII 表',
      desc: '常用 ASCII 码对照表:十进制/十六进制/字符,可搜索。',
      keywords: ['ascii 码表', 'ascii 对照表', 'ascii 十六进制'],
      stage: '③ 数据 / 文本处理',
      beginnerIntro: 'ASCII 是最基础的字符编码。这里是可搜索的对照表。',
      whenToUse: '查某个字符的编码、或某个码对应啥字符时。',
      whyTool: '完整对照 + 即时搜索,离线可用。',
    },
    en: {
      title: 'ASCII Table',
      short: 'ASCII Table',
      desc: 'A searchable ASCII reference table: decimal / hex / character.',
      keywords: ['ascii table', 'ascii chart', 'ascii hex'],
      stage: '③ Data / Text',
      beginnerIntro: 'ASCII is the most basic character encoding. Here is a searchable reference table.',
      whenToUse: "When looking up a character's code, or which character a code maps to.",
      whyTool: 'A complete reference with instant search, works offline.',
    },
  },
  {
    slug: 'dataurl',
    category: 'design',
    related: ['base64', 'image-compress', 'svg'],
    status: 'live',
    zh: {
      title: '图片转 Base64 / DataURL',
      short: '图片转 DataURL',
      desc: '把图片转成 Base64 DataURL,直接内嵌到 CSS/HTML。',
      keywords: ['图片转 base64', 'dataurl 生成', '图片内嵌 css', 'base64 图片'],
      stage: '① 设计 / 资源',
      beginnerIntro: '把小图片变成一串文本(DataURL),可以直接写进 CSS/HTML,少一次请求。',
      whenToUse: '想把小图标内联进代码、减少请求时。',
      whyTool: '本地转换不上传;同时给出 img 与 CSS background 用法。',
    },
    en: {
      title: 'Image to Base64 / DataURL',
      short: 'Image→DataURL',
      desc: 'Turn an image into a Base64 DataURL to embed directly in CSS/HTML.',
      keywords: ['image to base64', 'dataurl generator', 'embed image in css', 'base64 image'],
      stage: '① Design / Assets',
      beginnerIntro: 'Turn a small image into a string of text (DataURL) you can drop straight into CSS/HTML, saving a request.',
      whenToUse: 'When inlining a small icon into your code to cut a request.',
      whyTool: 'Converted locally, nothing uploaded; gives both img and CSS background usage.',
    },
  },
];

/** 把某语言的文案展开到工具对象上,页面代码照旧用 .title/.desc 等。 */
export function resolveTool(t: Tool, lang: import('../i18n').Lang): ResolvedTool {
  return { slug: t.slug, category: t.category, related: t.related, status: t.status, ...t[lang] };
}

export const getTools = (lang: import('../i18n').Lang): ResolvedTool[] =>
  tools.map((t) => resolveTool(t, lang));

export const liveTools = (lang: import('../i18n').Lang) =>
  getTools(lang).filter((t) => t.status === 'live');

export function getTool(slug: string, lang: import('../i18n').Lang): ResolvedTool | undefined {
  const t = tools.find((x) => x.slug === slug);
  return t ? resolveTool(t, lang) : undefined;
}
