// 工具注册表 —— 单一数据源:驱动首页列表、导航、面包屑、sitemap。
// 详见《技术方案.md》§4 与《入门层与开发流程.md》。

export type Category = 'config' | 'text' | 'dev' | 'design' | 'code' | 'seo';

export interface Tool {
  slug: string; // 'cron'
  title: string; // 全称(工具页 H1 / SEO 主词)
  short: string; // 短名(面包屑 / 导航)
  desc: string; // 一句话卖点(卡片 + meta description)
  category: Category;
  keywords: string[];
  related?: string[]; // 相关工具 slug(人工关联,可跨分类);不足时按同分类兜底。见《内链策略.md》§3
  status: 'live' | 'soon';
  // 入门层字段
  stage: string; // 开发流程阶段
  beginnerIntro: string; // 小白话:这是什么、干什么用
  whenToUse: string; // 什么时候会用到
  whyTool: string; // 为什么用它而不是问 AI
}

export const categoryLabels: Record<Category, string> = {
  config: '配置生成',
  text: '文本处理',
  dev: '开发辅助',
  design: '设计资源',
  code: '代码文档',
  seo: 'SEO / 站长',
};

export const tools: Tool[] = [
  {
    slug: 'cron',
    title: 'Cron 表达式生成器',
    short: 'Cron 生成器',
    desc: '可视化生成 crontab,自动人话解释,并预览未来执行时间。',
    category: 'config',
    keywords: ['cron 生成器', 'crontab 每5分钟', 'cron 表达式解释', 'cron 在线'],
    related: ['docker-compose', 'nginx', 'timezone'],
    status: 'live',
    stage: '⑥ 定时与运维',
    beginnerIntro: '定时任务:让服务器在你设定的时间(比如每天凌晨)自动执行命令,不用人工盯着。',
    whenToUse: '需要定时备份、定时清理、定时跑脚本时,用 cron 表达式描述"什么时候执行"。',
    whyTool: 'AI 可能编错 cron,这里用真实解析库即填即得,还能把 AI 给的表达式粘进来反向验证。',
  },
  {
    slug: 'regex',
    title: '正则表达式测试器',
    short: '正则测试',
    desc: '实时高亮匹配,分组解释,内置常用模板,粘贴即测。',
    category: 'text',
    keywords: ['在线正则测试', '正则可视化', '正则 匹配邮箱', 'regex 测试'],
    related: ['text-diff', 'table', 'json'],
    status: 'live',
    stage: '③ 数据 / 文本处理',
    beginnerIntro: '正则:用一串规则从文本里匹配或提取内容(如邮箱、手机号),不用写一堆判断。',
    whenToUse: '校验输入、批量提取、查找替换文本时。',
    whyTool: '浏览器原生实时高亮,改一处立刻看到匹配结果,还能验证 AI 写的正则对不对。',
  },
  {
    slug: 'nginx',
    title: 'Nginx 反向代理配置生成器',
    short: 'Nginx 配置',
    desc: '表单生成 server 配置,一键切换 Caddy,支持 HTTPS / WebSocket。',
    category: 'config',
    keywords: ['nginx 反向代理 配置', 'nginx websocket', 'caddy 反代', 'nginx 配置生成'],
    related: ['docker-compose', 'cron', 'ip'],
    status: 'live',
    stage: '⑥ 部署上线',
    beginnerIntro: '反向代理:把用户对你域名的访问转发给后台真正跑的程序,顺便管好 HTTPS。',
    whenToUse: '应用跑在服务器某端口上,想用域名 + 小绿锁对外提供访问时。',
    whyTool: '勾几个选项即出可用配置,不用背指令;AI 常编不存在的参数,这里可直接校验。',
  },
  {
    slug: 'docker-compose',
    title: 'Docker Compose 模板生成器',
    short: 'Docker Compose',
    desc: '挑选服务(nginx/postgres/redis…)拼出 compose 文件,复制即用。',
    category: 'config',
    keywords: ['docker compose 模板', 'docker compose postgres', 'docker-compose.yml'],
    related: ['nginx', 'cron', 'password'],
    status: 'live',
    stage: '⑤ 构建 / 打包',
    beginnerIntro: '用一个文件描述你的应用要跑哪些服务(网站、数据库…),一条命令全部启动。',
    whenToUse: '要把应用和依赖一起部署、一键启停时。',
    whyTool: '可视化拼装 + 语法校验,避免 YAML 缩进坑;可校验 AI 生成的 compose 是否合法。',
  },
  {
    slug: 'timestamp',
    title: 'Unix 时间戳转换',
    short: '时间戳转换',
    desc: 'Unix 时间戳与日期时间互转,自动识别秒/毫秒,含本地与 UTC。',
    category: 'dev',
    keywords: ['时间戳转换', 'unix 时间戳', '时间戳转日期', '当前时间戳'],
    related: ['timezone', 'cron', 'jwt'],
    status: 'live',
    stage: '④ 接口 / 调试',
    beginnerIntro: '时间戳是从 1970 年至今的秒数(或毫秒数),程序里常用它表示时间。这里在时间戳和人类可读日期之间互转。',
    whenToUse: '看到接口返回一串数字的时间、或要把日期转成时间戳存库时。',
    whyTool: '自动识别秒还是毫秒,同时给出本地时区、UTC 和 ISO,不用心算时区。',
  },
  {
    slug: 'base64',
    title: 'Base64 编码 / 解码',
    short: 'Base64',
    desc: '文本与 Base64 互转,支持中文(UTF-8),浏览器本地处理。',
    category: 'text',
    keywords: ['base64 编码', 'base64 解码', 'base64 转换', '在线 base64'],
    related: ['url-encode', 'jwt', 'dataurl'],
    status: 'live',
    stage: '③ 数据 / 文本处理',
    beginnerIntro: 'Base64 是把任意文本/数据编成只含字母数字的字符串的方式,常用于在文本环境里传输数据。',
    whenToUse: '需要把数据塞进 URL、JSON、配置或邮件等纯文本场景时。',
    whyTool: '正确处理中文(UTF-8),即时互转、可复制,不用担心编码错乱。',
  },
  {
    slug: 'url-encode',
    title: 'URL 编码 / 解码',
    short: 'URL 编解码',
    desc: '对 URL 参数进行百分号编码与解码,支持中文与特殊字符。',
    category: 'text',
    keywords: ['url 编码', 'url 解码', 'urlencode', '百分号编码'],
    related: ['base64', 'html-entity', 'json'],
    status: 'live',
    stage: '③ 数据 / 文本处理',
    beginnerIntro: 'URL 里不能直接放空格、中文等字符,需要编码成 %xx 形式。这里做 URL 编码与解码。',
    whenToUse: '拼接带中文/特殊字符的链接、或看到 %E4%B8%AD 这类乱码想还原时。',
    whyTool: '即时双向转换,可选整段 URL 或单个参数两种模式,结果准确可复制。',
  },
  {
    slug: 'uuid',
    title: 'UUID 生成器',
    short: 'UUID 生成',
    desc: '批量生成 UUID v4,支持大写、去连字符,一键复制。',
    category: 'dev',
    keywords: ['uuid 生成', 'guid 生成', 'uuid v4', '在线 uuid'],
    related: ['hash', 'password', 'jwt'],
    status: 'live',
    stage: '④ 接口 / 调试',
    beginnerIntro: 'UUID 是一串几乎不会重复的唯一标识,常用作数据库主键、请求 ID 等。',
    whenToUse: '需要一个全局唯一的 ID,又不想依赖数据库自增时。',
    whyTool: '用浏览器原生 crypto 生成,安全随机;可批量生成并一键复制。',
  },
  {
    slug: 'json',
    title: 'JSON 格式化 / 校验',
    short: 'JSON 格式化',
    desc: '格式化、压缩、校验 JSON,可排序键名,错误精准定位。',
    category: 'text',
    keywords: ['json 格式化', 'json 校验', 'json 压缩', '在线 json'],
    related: ['table', 'text-diff', 'url-encode'],
    status: 'live',
    stage: '③ 数据 / 文本处理',
    beginnerIntro: 'JSON 是接口和配置最常用的数据格式。这里把压成一行的 JSON 展开成易读格式,或反过来压缩,并校验是否合法。',
    whenToUse: '接口返回一坨挤在一起的 JSON、或要检查 JSON 写得对不对时。',
    whyTool: '本地即时格式化、语法报错定位;可校验 AI 生成的 JSON 是否合法。',
  },
  {
    slug: 'jwt',
    title: 'JWT 解码器',
    short: 'JWT 解码',
    desc: '解析 JWT 的 Header 与 Payload,自动展示过期/签发时间。',
    category: 'dev',
    keywords: ['jwt 解码', 'jwt 解析', 'token 解析', '在线 jwt'],
    related: ['base64', 'timestamp', 'hash'],
    status: 'live',
    stage: '④ 接口 / 调试',
    beginnerIntro: 'JWT 是登录后常见的一串 token,里面用 Base64 编了用户信息和有效期。这里把它解开看内容。',
    whenToUse: '调试登录/鉴权,想看 token 里存了什么、什么时候过期时。',
    whyTool: '本地解析不外传 token;自动把 exp/iat 时间戳转成可读日期,一眼看懂。',
  },
  {
    slug: 'gradient',
    title: 'CSS 渐变生成器',
    short: 'CSS 渐变',
    desc: '可视化调节颜色与角度,实时预览并生成 CSS 渐变代码。',
    category: 'design',
    keywords: ['css 渐变', 'linear-gradient 生成', '渐变背景 css', 'gradient generator'],
    related: ['color', 'contrast', 'playground'],
    status: 'live',
    stage: '① 设计 / 资源',
    beginnerIntro: '渐变就是颜色平滑过渡的背景。这里拖一拖就生成对应的 CSS 代码。',
    whenToUse: '想给按钮、卡片或页面背景做个渐变色时。',
    whyTool: '所见即所得,实时预览 + 直接出 CSS,不用背 linear-gradient 语法。',
  },
  {
    slug: 'color',
    title: '颜色转换器',
    short: '颜色转换',
    desc: 'HEX / RGB / HSL 互转,预览色块,并生成同色系深浅色阶。',
    category: 'design',
    keywords: ['颜色转换', 'hex 转 rgb', 'rgb 转 hsl', '颜色代码转换'],
    related: ['gradient', 'contrast', 'colorblind'],
    status: 'live',
    stage: '① 设计 / 资源',
    beginnerIntro: '在 HEX(#ff0000)、RGB、HSL 等颜色写法之间转换,并预览颜色。',
    whenToUse: '设计里拿到一种格式的颜色,代码里却要另一种格式时。',
    whyTool: '一次看到三种格式 + 色块预览 + 深浅色阶,点一下即复制。',
  },
  {
    slug: 'image-compress',
    title: '图片压缩',
    short: '图片压缩',
    desc: '本地压缩 JPG / PNG / WebP,可调质量与尺寸,不上传服务器。',
    category: 'design',
    keywords: ['图片压缩', '在线压缩图片', 'webp 转换', '图片变小'],
    related: ['svg', 'dataurl', 'favicon'],
    status: 'live',
    stage: '① 设计 / 资源',
    beginnerIntro: '在基本不影响观感的前提下,把图片文件变小,加快网页加载。',
    whenToUse: '图片太大拖慢网站,或要满足上传大小限制时。',
    whyTool: '全程在浏览器本地压缩,图片不上传,隐私安全且即时出结果。',
  },
  {
    slug: 'markdown-table',
    title: 'Markdown 表格生成器',
    short: 'MD 表格',
    desc: '可视化填表格 + 设置列对齐,实时生成 Markdown 表格代码。',
    category: 'code',
    keywords: ['markdown 表格', 'md 表格生成', 'markdown table 生成器'],
    related: ['table', 'html-to-markdown', 'tree'],
    status: 'live',
    stage: '② 编码 / 演练',
    beginnerIntro: 'Markdown 手写表格容易对不齐。这里填个表格,自动生成规整的 Markdown 代码。',
    whenToUse: '在 README、文档或 GitHub issue 里要插入表格时。',
    whyTool: '可视化编辑 + 列对齐设置,自动对齐生成,免手敲竖线和分隔线。',
  },
  {
    slug: 'password',
    title: '密码生成器',
    short: '密码生成',
    desc: '生成高强度随机密码,可选长度与字符集,基于安全随机源。',
    category: 'dev',
    keywords: ['密码生成器', '随机密码', '强密码生成', 'password generator'],
    related: ['hash', 'uuid', 'jwt'],
    status: 'live',
    stage: '④ 接口 / 调试',
    beginnerIntro: '生成又长又随机、难被猜到的密码。',
    whenToUse: '注册账号、设置数据库或服务器密码时。',
    whyTool: '用浏览器安全随机源本地生成,不联网、不记录,可调长度与字符集。',
  },
  {
    slug: 'hash',
    title: 'Hash 生成器',
    short: 'Hash 生成',
    desc: '计算文本的 SHA-1 / SHA-256 / SHA-384 / SHA-512 哈希值。',
    category: 'dev',
    keywords: ['hash 生成', 'sha256 在线', '哈希计算', 'sha512'],
    related: ['uuid', 'password', 'base64'],
    status: 'live',
    stage: '④ 接口 / 调试',
    beginnerIntro: '把任意文本转成固定长度的"指纹"(哈希),常用于校验一致性。',
    whenToUse: '校验文件/文本是否被改动,或存储密码摘要时。',
    whyTool: '基于浏览器原生 Web Crypto 本地计算,数据不外传。',
  },
  {
    slug: 'timezone',
    title: '时区转换器',
    short: '时区转换',
    desc: '把一个时间换算到全球多个时区,自动处理夏令时。',
    category: 'dev',
    keywords: ['时区转换', 'utc 转北京时间', '时差换算', 'timezone converter'],
    related: ['timestamp', 'cron', 'ip'],
    status: 'live',
    stage: '④ 接口 / 调试',
    beginnerIntro: '把某个时间点换算成不同城市/时区的当地时间。',
    whenToUse: '跨时区安排会议,或看国外服务器/日志时间时。',
    whyTool: '基于浏览器 Intl 时区库,自动处理夏令时,即时换算。',
  },
  {
    slug: 'tree',
    title: '目录树生成器',
    short: '目录树',
    desc: '把缩进列表转成 ├── └── 形式的 ASCII 目录树。',
    category: 'dev',
    keywords: ['目录树生成', 'ascii 树', '文件结构 树状图', 'tree 生成'],
    related: ['markdown-table', 'json', 'docker-compose'],
    status: 'live',
    stage: '⑤ 构建 / 打包',
    beginnerIntro: '把用缩进写的文件/目录列表,变成漂亮的树状图。',
    whenToUse: '写 README 展示项目结构时。',
    whyTool: '边写边出树状图,复制即用,免手敲制表符和连线。',
  },
  {
    slug: 'ua',
    title: 'UserAgent 解析器',
    short: 'UA 解析',
    desc: '解析 User-Agent 字符串,识别浏览器、系统与设备类型。',
    category: 'dev',
    keywords: ['useragent 解析', 'ua 解析', 'user-agent 查询'],
    related: ['ip', 'timezone', 'json'],
    status: 'live',
    stage: '④ 接口 / 调试',
    beginnerIntro: 'User-Agent 是浏览器自报身份的一串文本。这里把它解析成浏览器/系统等信息。',
    whenToUse: '排查兼容性问题,或看日志里的 UA 时。',
    whyTool: '默认填入你当前浏览器的 UA,本地解析,不上传。',
  },
  {
    slug: 'meta',
    title: 'Meta 标签长度检测',
    short: 'Meta 检测',
    desc: '检测 title/description 的字符与像素长度,并预览 Google 搜索结果。',
    category: 'seo',
    keywords: ['title 长度检测', 'meta description 长度', 'serp 预览', 'seo 标题'],
    related: ['og', 'qrcode', 'favicon'],
    status: 'live',
    stage: '⑧ 发布 / SEO',
    beginnerIntro: 'SEO 里标题和描述太长会被搜索引擎截断。这里检测长度并预览显示效果。',
    whenToUse: '给网页写 SEO 标题和描述时。',
    whyTool: '同时看字符数、像素宽度和搜索结果预览,超限即时提示。',
  },
  {
    slug: 'ip',
    title: 'IP 地址查询',
    short: 'IP 查询',
    desc: '查询你的公网 IP 及归属地、运营商等信息。',
    category: 'dev',
    keywords: ['ip 查询', '公网 ip', '我的 ip', 'ip 归属地'],
    related: ['ua', 'nginx', 'timezone'],
    status: 'live',
    stage: '④ 接口 / 调试',
    beginnerIntro: '查看你当前的公网 IP 地址,以及它的大致归属地和运营商。',
    whenToUse: '排查网络、确认出口 IP、检查是否走了代理时。',
    whyTool: '需要服务器才能看到你的公网 IP,由 DevBox 后端返回,不记录你的查询。',
  },
  {
    slug: 'qrcode',
    title: '二维码生成器',
    short: '二维码生成',
    desc: '把文本 / 链接生成二维码,可调尺寸与容错级别,下载 PNG。',
    category: 'design',
    keywords: ['二维码生成', '在线二维码', 'qrcode 生成', '网址转二维码'],
    related: ['og', 'meta', 'favicon'],
    status: 'live',
    stage: '⑧ 发布 / SEO',
    beginnerIntro: '把一段文字或网址变成二维码图片,手机扫一扫就能打开。',
    whenToUse: '要让别人扫码访问链接、加好友、看名片时。',
    whyTool: '本地即时生成、可下载 PNG,内容不上传服务器。',
  },
  {
    slug: 'og',
    title: 'Open Graph 预览',
    short: 'OG 预览',
    desc: '预览分享到社交平台的卡片效果,并生成 OG / Twitter 标签。',
    category: 'seo',
    keywords: ['open graph 预览', 'og 标签生成', '分享卡片预览', 'og image'],
    related: ['meta', 'qrcode', 'favicon'],
    status: 'live',
    stage: '⑧ 发布 / SEO',
    beginnerIntro: '网页被分享到微信/X 等平台时会显示一张卡片,这里预览它并生成对应标签。',
    whenToUse: '做完页面、想让分享出去好看时。',
    whyTool: '实时预览卡片 + 一键生成 og:/twitter: 标签,免反复发帖测试。',
  },
  {
    slug: 'semver',
    title: 'Semver 版本工具',
    short: 'Semver',
    desc: '校验语义化版本、判断是否满足范围、解析与比较版本号。',
    category: 'dev',
    keywords: ['semver', '语义化版本', '版本范围 满足', 'npm 版本'],
    related: ['json', 'docker-compose', 'uuid'],
    status: 'live',
    stage: '⑤ 构建 / 打包',
    beginnerIntro: 'Semver 是 1.2.3 这样的版本号规则。这里判断版本是否合法、是否满足 ^1.0.0 之类的范围。',
    whenToUse: '看 package.json 依赖范围、确认某版本是否匹配时。',
    whyTool: '基于官方 semver 库本地计算,范围判断准确,免手算。',
  },
  {
    slug: 'html-to-markdown',
    title: 'HTML 转 Markdown',
    short: 'HTML→MD',
    desc: '把 HTML 转换成 Markdown,保留标题、列表、链接、代码等。',
    category: 'code',
    keywords: ['html 转 markdown', 'html to markdown', '网页转 md'],
    related: ['markdown-table', 'html-entity', 'playground'],
    status: 'live',
    stage: '② 编码 / 演练',
    beginnerIntro: '把一段 HTML 代码转成等价的 Markdown 文本。',
    whenToUse: '把网页内容搬进 Markdown 文档/笔记时。',
    whyTool: '本地即时转换,保留结构,可校验 AI 转出来的 Markdown 是否正确。',
  },
  {
    slug: 'playground',
    title: '代码演练场(HTML/CSS/JS)',
    short: '代码演练',
    desc: '在线编写 HTML/CSS/JS,右侧沙箱实时预览效果。',
    category: 'code',
    keywords: ['html 在线运行', 'css js 演练', '前端 playground', '在线代码运行'],
    related: ['gradient', 'color', 'html-to-markdown'],
    status: 'live',
    stage: '② 编码 / 演练',
    beginnerIntro: '一个能马上看到效果的前端练习场:左边写 HTML/CSS/JS,右边实时显示。',
    whenToUse: '快速试一段样式/脚本、做最小复现时。',
    whyTool: '在隔离沙箱里运行,即写即看,代码不上传。',
  },
  {
    slug: 'favicon',
    title: 'Favicon 生成器',
    short: 'Favicon',
    desc: '上传图片生成多尺寸 PNG 图标,并给出 HTML 引用代码。',
    category: 'design',
    keywords: ['favicon 生成', '网站图标生成', 'favicon 制作', '图标尺寸'],
    related: ['svg', 'image-compress', 'qrcode'],
    status: 'live',
    stage: '① 设计 / 资源',
    beginnerIntro: 'Favicon 是浏览器标签页上的小图标。上传一张图,生成各种尺寸。',
    whenToUse: '给网站配标签页图标时。',
    whyTool: '本地用 Canvas 生成各尺寸并给出引用代码,图片不上传。',
  },
  {
    slug: 'svg',
    title: 'SVG 压缩',
    short: 'SVG 压缩',
    desc: '去除注释与冗余空白,压缩 SVG 体积,显示压缩前后大小。',
    category: 'design',
    keywords: ['svg 压缩', 'svg 优化', 'svg 变小', 'svg minify'],
    related: ['favicon', 'image-compress', 'dataurl'],
    status: 'live',
    stage: '① 设计 / 资源',
    beginnerIntro: '把 SVG 图标里多余的注释和空白去掉,让文件更小。',
    whenToUse: '把 SVG 图标放进项目、想减小体积时。',
    whyTool: '本地即时压缩、可复制,展示压缩率,数据不上传。',
  },
  {
    slug: 'text-diff',
    title: '文本 Diff 对比',
    short: '文本 Diff',
    desc: '逐行比较两段文本,高亮新增、删除与修改,统计差异。',
    category: 'text',
    keywords: ['文本对比', 'diff 在线', '文本差异', '代码对比'],
    related: ['regex', 'json', 'table'],
    status: 'live',
    stage: '③ 数据 / 文本处理',
    beginnerIntro: '把两段文本并排比,标出哪些行加了、删了、改了。',
    whenToUse: '对比两个版本的配置/代码/文案有什么不同时。',
    whyTool: '本地即时逐行 diff,颜色高亮一目了然,内容不上传。',
  },
  {
    slug: 'table',
    title: '表格转换器',
    short: '表格转换',
    desc: 'CSV / JSON / Markdown / YAML / HTML 表格任意互转,复制即用。',
    category: 'text',
    keywords: ['csv 转 json', 'json 转 markdown', 'csv 转 markdown', '表格转换'],
    related: ['json', 'markdown-table', 'text-diff'],
    status: 'live',
    stage: '③ 数据 / 文本处理',
    beginnerIntro: '把表格数据在 CSV、JSON、Markdown、YAML、HTML 等格式之间来回转换。',
    whenToUse: '拿到一种格式的表格数据,却要另一种格式时。',
    whyTool: '五种格式两两互转、本地即时处理;可校验 AI 转出来的结构是否正确。',
  },
  {
    slug: 'contrast',
    title: '颜色对比度检测',
    short: '对比度检测',
    desc: '计算两色对比度,按 WCAG 判断可读性(AA/AAA)。',
    category: 'design',
    keywords: ['对比度计算', 'wcag 对比度', '颜色可读性', 'contrast ratio'],
    related: ['color', 'colorblind', 'gradient'],
    status: 'live',
    stage: '① 设计 / 资源',
    beginnerIntro: '检查文字色和背景色的对比够不够,避免看不清。',
    whenToUse: '定文字/背景配色、做无障碍(a11y)检查时。',
    whyTool: '按 WCAG 标准即时给出对比度和 AA/AAA 是否达标。',
  },
  {
    slug: 'colorblind',
    title: '色盲模拟',
    short: '色盲模拟',
    desc: '模拟颜色在红绿色盲等色觉障碍下的显示效果。',
    category: 'design',
    keywords: ['色盲模拟', '色觉障碍', '色盲 颜色', 'color blindness'],
    related: ['contrast', 'color', 'gradient'],
    status: 'live',
    stage: '① 设计 / 资源',
    beginnerIntro: '看看你的配色在色盲用户眼里大概是什么样。',
    whenToUse: '做无障碍设计、确认配色是否易区分时。',
    whyTool: '即时模拟多种色觉类型,帮你避开难以区分的配色。',
  },
  {
    slug: 'html-entity',
    title: 'HTML 实体编解码',
    short: 'HTML 实体',
    desc: '在字符与 HTML 实体(&amp; &#39; 等)之间互转。',
    category: 'text',
    keywords: ['html 实体', 'html 转义', 'html entity 编码', '实体解码'],
    related: ['url-encode', 'unicode', 'html-to-markdown'],
    status: 'live',
    stage: '③ 数据 / 文本处理',
    beginnerIntro: '把 < > & 等特殊字符转成 HTML 实体,或反过来还原。',
    whenToUse: '把代码/符号安全地放进 HTML,或还原网页里的实体时。',
    whyTool: '即时双向转换,浏览器本地处理。',
  },
  {
    slug: 'unicode',
    title: 'Unicode / 编码查看',
    short: 'Unicode 查看',
    desc: '查看文本的 Unicode 码点与 UTF-8 / UTF-16 编码。',
    category: 'text',
    keywords: ['unicode 码点', 'utf-8 编码', '字符编码查看', 'code point'],
    related: ['ascii', 'html-entity', 'base64'],
    status: 'live',
    stage: '③ 数据 / 文本处理',
    beginnerIntro: '看一段文字里每个字符的 Unicode 码点和字节编码。',
    whenToUse: '排查乱码、看 emoji/特殊字符编码时。',
    whyTool: '逐字符列出码点与 UTF-8/16 字节,本地即时计算。',
  },
  {
    slug: 'ascii',
    title: 'ASCII 码表',
    short: 'ASCII 表',
    desc: '常用 ASCII 码对照表:十进制/十六进制/字符,可搜索。',
    category: 'text',
    keywords: ['ascii 码表', 'ascii 对照表', 'ascii 十六进制'],
    related: ['unicode', 'html-entity', 'base64'],
    status: 'live',
    stage: '③ 数据 / 文本处理',
    beginnerIntro: 'ASCII 是最基础的字符编码。这里是可搜索的对照表。',
    whenToUse: '查某个字符的编码、或某个码对应啥字符时。',
    whyTool: '完整对照 + 即时搜索,离线可用。',
  },
  {
    slug: 'dataurl',
    title: '图片转 Base64 / DataURL',
    short: '图片转 DataURL',
    desc: '把图片转成 Base64 DataURL,直接内嵌到 CSS/HTML。',
    category: 'design',
    keywords: ['图片转 base64', 'dataurl 生成', '图片内嵌 css', 'base64 图片'],
    related: ['base64', 'image-compress', 'svg'],
    status: 'live',
    stage: '① 设计 / 资源',
    beginnerIntro: '把小图片变成一串文本(DataURL),可以直接写进 CSS/HTML,少一次请求。',
    whenToUse: '想把小图标内联进代码、减少请求时。',
    whyTool: '本地转换不上传;同时给出 img 与 CSS background 用法。',
  },
];

export const liveTools = () => tools.filter((t) => t.status === 'live');
export const getTool = (slug: string) => tools.find((t) => t.slug === slug);
